### PR TITLE
Start a section that elaborates on the concept of branches and branching

### PR DESCRIPTION
**Pull request by adswa**
This is work in progress on an extra lesson about Git branches, how to branch, and how to perform collaborative workflows with a focus on concepts rather than actionable walk-throughs.
It can complement the first episode, but also the fourth one.

TODOs:
- [x] tweak the text. Apart from fine tuning it needs additional motivation and examples for branches
- [x] Add forks into the overview
- [x] Add screenshots from Github
- [x] Add screenshots from Git
- [ ] inlcude more general elements, e.g. an exercise at the end of the episode.

### CODE REVIEW

**Comment by adswa** [comment]
Corresponding slides are developed in https://github.com/datalad-handbook/course/pull/47

**Comment by adswa** [comment]
I think this is good to go from my point of view. I decided against an exercise at the end of the episode for now - it already contains an exercise in the middle, and other content is more pressing time wise. Are you fine with me merging this, @mslw ?

**Comment by mslw** [comment]
Looks great! I read it all and made some minor typo changes. It's definitely worthy of a merge @adswa ;)

**Comment by adswa** [comment]
Thanks a lot for the fixes!

**Pull request merged**
